server:
  port: 8083

spring:
#  datasource:
#    url: jdbc:postgresql://postgres-db:5432/postgresIndividualApi
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://keycloak:8080/realms/alchim
          jwk-set-uri: http://keycloak:8080/realms/alchim/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/alchim
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: reactive-springsecurity-client  #resource
            client-secret: ${REALM_ALCHIM_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email


logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.web.servlet.filter: DEBUG
